config/routes.rb
Rails.application.routes.draw do
  get root to: 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end


  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to :books
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div class="edit-book">
  <h1>Editing Book</h1>
  <% if @book.errors.any? %>
    <h2 class="error-message"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul  class="error-list">
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

    <p>Title</p>
    <%= f.text_field :title %>

    <p class="edit">Body</p>
    <%= f.text_area :body %>

    <p class="edit"><%= f.submit 'Update Book' %></p>

  <% end %>

  <p class="edit">
    <%= link_to 'Show', book_path(@book.id) %>
    |
    <%= link_to 'Back', books_path %>
  </p>
</div>

app/views/books/index.html.erb
<div class="index-book">
  <h1>Books</h1>
  <table class="book-list">
    <thead>
      <th>Title</th>
      <th>Body</th>
      <th></th>
    </thead>
    <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td nowrap>
          <%= link_to 'Show', book_path(book.id) %>
          <%= link_to 'Edit', edit_book_path(book.id) %>
          <%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="new-book">
    <h2 class="new-title">New book</h2>
    <% if @book.errors.any? %>
      <h2 class="error-message"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul class="error-list">
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_with model: @book, url: '/books', method: :post do |f| %>

      <p>Title</p>
      <%= f.text_field :title %>

      <p class="new">Body</p>
      <%= f.text_area :body %>

      <p class="new"><%= f.submit 'Create Book' %></p>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="show-book">
  <p class="flash">
    <%= flash[:success] %>
  </p>
  <p>
    <strong>Title:</strong>
    <%= @book.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @book.body %>
  </p>

<%= link_to "Edit", edit_book_path(@book.id) %>
|
<%= link_to "Back", books_path %>
</div>

app/views/homes/top.html.erb
<div class="top-page">
  <h1>ようこそ Bookers へ!</h1>

  <p class="top-text1">Bookersでは、さまざまな書籍に関するあなたの意見や</p>
  <p class="top-text2">印象を共有し交換することができます</p>

  <p class="index-link"><%= link_to 'start', books_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>